{"game_date": "October 3, 2018, 10:30 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Max Comtois", "Cam Fowler", "Ryan Getzlaf", "Adam Henrique", "Hampus Lindholm", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Carter Rowney", "Luke Schenn", "Kiefer Sherwood", "Jakob Silfverberg", "Sam Steel", "Ben Street", "Troy Terry"]}
{"game_date": "October 21, 2018, 8:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Max Comtois", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ryan Kesler", "Hampus Lindholm", "Isac Lundestrom", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Kiefer Sherwood", "Sam Steel", "Ben Street", "Andrej Sustr"]}
{"game_date": "October 20, 2018, 10:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Max Comtois", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ryan Kesler", "Hampus Lindholm", "Isac Lundestrom", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Luke Schenn", "Kiefer Sherwood", "Sam Steel", "Ben Street"]}
{"game_date": "November 6, 2018, 10:30 PM", "skater_list": ["", "Pontus Aberg", "Sam Carrick", "Andrew Cogliano", "Patrick Eaves", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Kiefer Sherwood", "Jakob Silfverberg", "Ben Street", "Andy Welinski"]}
{"game_date": "November 4, 2018, 9:00 PM", "skater_list": ["", "Pontus Aberg", "Sam Carrick", "Andrew Cogliano", "Patrick Eaves", "Cam Fowler", "Brian Gibbons", "Adam Henrique", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Isac Lundestrom", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Kiefer Sherwood", "Jakob Silfverberg", "Ben Street", "Andy Welinski"]}
{"game_date": "October 30, 2018, 10:00 PM", "skater_list": ["", "Pontus Aberg", "Joseph Blandisi", "Andrew Cogliano", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Isac Lundestrom", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Jakob Silfverberg", "Sam Steel", "Ben Street", "Andy Welinski"]}
{"game_date": "October 28, 2018, 8:00 PM", "skater_list": ["", "Pontus Aberg", "Joseph Blandisi", "Andrew Cogliano", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Isac Lundestrom", "Josh Manson", "Brandon Montour", "Rickard Rakell", "Kiefer Sherwood", "Jakob Silfverberg", "Sam Steel", "Andy Welinski"]}
{"game_date": "October 23, 2018, 8:30 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Max Comtois", "Cam Fowler", "Ryan Getzlaf", "Adam Henrique", "Ryan Kesler", "Hampus Lindholm", "Isac Lundestrom", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Nick Ritchie", "Luke Schenn", "Kiefer Sherwood", "Sam Steel", "Ben Street"]}
{"game_date": "October 25, 2018, 8:30 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ryan Kesler", "Hampus Lindholm", "Isac Lundestrom", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Nick Ritchie", "Luke Schenn", "Kiefer Sherwood", "Sam Steel", "Ben Street"]}
{"game_date": "November 1, 2018, 10:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Patrick Eaves", "Cam Fowler", "Ryan Getzlaf", "Adam Henrique", "Ryan Kesler", "Kalle Kossila", "Jacob Larsson", "Hampus Lindholm", "Isac Lundestrom", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Kiefer Sherwood", "Jakob Silfverberg", "Ben Street", "Andy Welinski"]}
{"game_date": "October 14, 2018, 7:00 PM", "skater_list": ["", "Andrew Cogliano", "Max Comtois", "Cam Fowler", "Brian Gibbons", "Adam Henrique", "Ryan Kesler", "Hampus Lindholm", "Isac Lundestrom", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Kiefer Sherwood", "Jakob Silfverberg", "Sam Steel", "Ben Street", "Andrej Sustr", "Troy Terry"]}
{"game_date": "October 13, 2018, 8:00 PM", "skater_list": ["", "Andrew Cogliano", "Max Comtois", "Cam Fowler", "Brian Gibbons", "Adam Henrique", "Ryan Kesler", "Hampus Lindholm", "Isac Lundestrom", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Carter Rowney", "Luke Schenn", "Kiefer Sherwood", "Jakob Silfverberg", "Sam Steel", "Ben Street"]}
{"game_date": "October 10, 2018, 10:00 PM", "skater_list": ["", "Andrew Cogliano", "Max Comtois", "Cam Fowler", "Adam Henrique", "Ryan Kesler", "Hampus Lindholm", "Isac Lundestrom", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Sam Steel", "Ben Street", "Andrej Sustr", "Troy Terry"]}
{"game_date": "October 17, 2018, 10:00 PM", "skater_list": ["", "Joseph Blandisi", "Andrew Cogliano", "Max Comtois", "Cam Fowler", "Brian Gibbons", "Adam Henrique", "Ryan Kesler", "Hampus Lindholm", "Isac Lundestrom", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Luke Schenn", "Kiefer Sherwood", "Sam Steel", "Ben Street", "Troy Terry"]}
{"game_date": "October 8, 2018, 10:00 PM", "skater_list": ["", "Andrew Cogliano", "Max Comtois", "Cam Fowler", "Brian Gibbons", "Adam Henrique", "Hampus Lindholm", "Isac Lundestrom", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Carter Rowney", "Luke Schenn", "Kiefer Sherwood", "Jakob Silfverberg", "Sam Steel", "Ben Street", "Troy Terry"]}
{"game_date": "December 20, 2018, 7:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Jake Dotchin", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Mahura", "Josh Manson", "Brandon Montour", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Daniel Sprong"]}
{"game_date": "October 6, 2018, 9:00 PM", "skater_list": ["", "Andrew Cogliano", "Max Comtois", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Hampus Lindholm", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Sam Steel", "Ben Street", "Andrej Sustr", "Troy Terry"]}
{"game_date": "March 30, 2019, 10:00 PM", "skater_list": ["", "Sam Carrick", "Chase De Leo", "Cam Fowler", "Derek Grant", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Jacob Larsson", "Hampus Lindholm", "Corey Perry", "Rickard Rakell", "Carter Rowney", "Kiefer Sherwood", "Devin Shore", "Jakob Silfverberg", "Sam Steel", "Andy Welinski"]}
{"game_date": "April 5, 2019, 10:00 PM", "skater_list": ["", "Cam Fowler", "Ryan Getzlaf", "Derek Grant", "Brendan Guhle", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Jacob Larsson", "Hampus Lindholm", "Jaycob Megna", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong", "Sam Steel"]}
{"game_date": "April 3, 2019, 10:30 PM", "skater_list": ["", "Cam Fowler", "Ryan Getzlaf", "Derek Grant", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Jacob Larsson", "Hampus Lindholm", "Jaycob Megna", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong", "Sam Steel", "Andy Welinski"]}
{"game_date": "March 29, 2019, 9:00 PM", "skater_list": ["", "Cam Fowler", "Derek Grant", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Jacob Larsson", "Hampus Lindholm", "Jaycob Megna", "Corey Perry", "Rickard Rakell", "Carter Rowney", "Kiefer Sherwood", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong", "Sam Steel", "Troy Terry", "Andy Welinski"]}
{"game_date": "March 26, 2019, 10:00 PM", "skater_list": ["", "Cam Fowler", "Derek Grant", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Corey Perry", "Rickard Rakell", "Carter Rowney", "Kiefer Sherwood", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong", "Sam Steel", "Troy Terry", "Andy Welinski"]}
{"game_date": "March 22, 2019, 10:00 PM", "skater_list": ["", "Cam Fowler", "Ryan Getzlaf", "Derek Grant", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong", "Troy Terry", "Andy Welinski"]}
{"game_date": "March 23, 2019, 10:30 PM", "skater_list": ["", "Cam Fowler", "Derek Grant", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Corey Perry", "Rickard Rakell", "Carter Rowney", "Kiefer Sherwood", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong", "Sam Steel", "Troy Terry", "Andy Welinski"]}
{"game_date": "March 17, 2019, 9:00 PM", "skater_list": ["", "Cam Fowler", "Ryan Getzlaf", "Derek Grant", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Jacob Larsson", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong", "Troy Terry"]}
{"game_date": "March 20, 2019, 10:00 PM", "skater_list": ["", "Cam Fowler", "Ryan Getzlaf", "Derek Grant", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong", "Troy Terry", "Andy Welinski"]}
{"game_date": "March 12, 2019, 10:00 PM", "skater_list": ["", "Cam Fowler", "Ryan Getzlaf", "Derek Grant", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Jacob Larsson", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong", "Troy Terry"]}
{"game_date": "March 10, 2019, 10:00 PM", "skater_list": ["", "Cam Fowler", "Ryan Getzlaf", "Derek Grant", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Jacob Larsson", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong", "Troy Terry"]}
{"game_date": "March 15, 2019, 9:00 PM", "skater_list": ["", "Cam Fowler", "Ryan Getzlaf", "Derek Grant", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Jacob Larsson", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong", "Troy Terry"]}
{"game_date": "March 8, 2019, 10:00 PM", "skater_list": ["", "Cam Fowler", "Ryan Getzlaf", "Derek Grant", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Jacob Larsson", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong", "Troy Terry"]}
{"game_date": "March 14, 2019, 10:00 PM", "skater_list": ["", "Cam Fowler", "Ryan Getzlaf", "Derek Grant", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Jacob Larsson", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong", "Troy Terry"]}
{"game_date": "March 5, 2019, 9:00 PM", "skater_list": ["", "Cam Fowler", "Ryan Getzlaf", "Brendan Guhle", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Ryan Kesler", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Corey Perry", "Rickard Rakell", "Carter Rowney", "Kevin Roy", "Jakob Silfverberg", "Daniel Sprong", "Sam Steel", "Troy Terry"]}
{"game_date": "March 6, 2019, 10:00 PM", "skater_list": ["", "Cam Fowler", "Ryan Getzlaf", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Kevin Roy", "Jakob Silfverberg", "Sam Steel", "Troy Terry"]}
{"game_date": "March 1, 2019, 10:00 PM", "skater_list": ["", "Cam Fowler", "Derek Grant", "Brendan Guhle", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Ryan Kesler", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong", "Troy Terry"]}
{"game_date": "February 27, 2019, 10:00 PM", "skater_list": ["", "Cam Fowler", "Derek Grant", "Brendan Guhle", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Ryan Kesler", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong", "Troy Terry"]}
{"game_date": "March 3, 2019, 4:00 PM", "skater_list": ["", "Cam Fowler", "Ryan Getzlaf", "Brendan Guhle", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Ryan Kesler", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Corey Perry", "Rickard Rakell", "Carter Rowney", "Kevin Roy", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong", "Troy Terry"]}
{"game_date": "February 25, 2019, 10:00 PM", "skater_list": ["", "Cam Fowler", "Derek Grant", "Brendan Guhle", "Adam Henrique", "Korbinian Holzer", "Max Jones", "Ryan Kesler", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong", "Troy Terry"]}
{"game_date": "February 23, 2019, 10:00 PM", "skater_list": ["", "Michael Del Zotto", "Cam Fowler", "Derek Grant", "Adam Henrique", "Max Jones", "Ryan Kesler", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Brandon Montour", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Sam Steel", "Troy Terry"]}
{"game_date": "February 19, 2019, 8:00 PM", "skater_list": ["", "Michael Del Zotto", "Cam Fowler", "Ryan Getzlaf", "Derek Grant", "Adam Henrique", "Max Jones", "Ryan Kesler", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Brandon Montour", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Troy Terry"]}
{"game_date": "February 22, 2019, 9:00 PM", "skater_list": ["", "Michael Del Zotto", "Cam Fowler", "Brian Gibbons", "Derek Grant", "Adam Henrique", "Max Jones", "Ryan Kesler", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Brandon Montour", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Troy Terry"]}
{"game_date": "February 15, 2019, 10:00 PM", "skater_list": ["", "Michael Del Zotto", "Cam Fowler", "Ryan Getzlaf", "Derek Grant", "Adam Henrique", "Max Jones", "Ryan Kesler", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Brandon Montour", "Corey Perry", "Rickard Rakell", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong", "Troy Terry"]}
{"game_date": "February 13, 2019, 10:30 PM", "skater_list": ["", "Michael Del Zotto", "Cam Fowler", "Ryan Getzlaf", "Derek Grant", "Adam Henrique", "Max Jones", "Ryan Kesler", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Brandon Montour", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong"]}
{"game_date": "February 5, 2019, 7:30 PM", "skater_list": ["", "Adam Cracknell", "Michael Del Zotto", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ryan Kesler", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Brandon Montour", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong"]}
{"game_date": "February 9, 2019, 1:00 PM", "skater_list": ["", "Michael Del Zotto", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Derek Grant", "Adam Henrique", "Ryan Kesler", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Brandon Montour", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong"]}
{"game_date": "February 17, 2019, 9:00 PM", "skater_list": ["", "Michael Del Zotto", "Cam Fowler", "Ryan Getzlaf", "Derek Grant", "Adam Henrique", "Max Jones", "Ryan Kesler", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Brandon Montour", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Troy Terry"]}
{"game_date": "February 7, 2019, 7:30 PM", "skater_list": ["", "Michael Del Zotto", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Derek Grant", "Adam Henrique", "Ryan Kesler", "Hampus Lindholm", "Josh Manson", "Jaycob Megna", "Brandon Montour", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong"]}
{"game_date": "February 4, 2019, 7:00 PM", "skater_list": ["", "Michael Del Zotto", "Patrick Eaves", "Cam Fowler", "Ryan Getzlaf", "Derek Grant", "Adam Henrique", "Korbinian Holzer", "Ryan Kesler", "Hampus Lindholm", "Josh Manson", "Brandon Montour", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong"]}
{"game_date": "February 2, 2019, 7:00 PM", "skater_list": ["", "Michael Del Zotto", "Patrick Eaves", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Derek Grant", "Adam Henrique", "Korbinian Holzer", "Hampus Lindholm", "Josh Manson", "Brandon Montour", "Corey Perry", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong"]}
{"game_date": "January 23, 2019, 10:00 PM", "skater_list": ["", "Sam Carrick", "Adam Cracknell", "Michael Del Zotto", "Cam Fowler", "Ryan Getzlaf", "Derek Grant", "Adam Henrique", "Max Jones", "Hampus Lindholm", "Josh Manson", "Brandon Montour", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Daniel Sprong", "Troy Terry", "Andy Welinski"]}
{"game_date": "January 20, 2019, 3:00 PM", "skater_list": ["", "Sam Carrick", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Derek Grant", "Adam Henrique", "Max Jones", "Jacob Larsson", "Hampus Lindholm", "Josh Manson", "Brandon Montour", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Daniel Sprong", "Troy Terry", "Andy Welinski"]}
{"game_date": "January 17, 2019, 8:00 PM", "skater_list": ["", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Derek Grant", "Adam Henrique", "Max Jones", "Ondrej Kase", "Jacob Larsson", "Hampus Lindholm", "Josh Manson", "Brandon Montour", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Daniel Sprong", "Troy Terry", "Andy Welinski"]}
{"game_date": "January 15, 2019, 7:30 PM", "skater_list": ["", "Jake Dotchin", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Manson", "Brandon Montour", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Devin Shore", "Jakob Silfverberg", "Daniel Sprong"]}
{"game_date": "January 13, 2019, 6:00 PM", "skater_list": ["", "Andrew Cogliano", "Jake Dotchin", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Manson", "Brandon Montour", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Daniel Sprong"]}
{"game_date": "January 11, 2019, 10:00 PM", "skater_list": ["", "Andrew Cogliano", "Jake Dotchin", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Manson", "Brandon Montour", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Daniel Sprong"]}
{"game_date": "January 19, 2019, 1:00 PM", "skater_list": ["", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Derek Grant", "Adam Henrique", "Max Jones", "Justin Kloos", "Jacob Larsson", "Hampus Lindholm", "Josh Manson", "Brandon Montour", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Devin Shore", "Daniel Sprong", "Troy Terry", "Andy Welinski"]}
{"game_date": "January 9, 2019, 10:00 PM", "skater_list": ["", "Andrew Cogliano", "Jake Dotchin", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Manson", "Brandon Montour", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Daniel Sprong"]}
{"game_date": "January 6, 2019, 8:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Hampus Lindholm", "Josh Mahura", "Josh Manson", "Brandon Montour", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Daniel Sprong", "Andy Welinski"]}
{"game_date": "January 4, 2019, 10:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Mahura", "Josh Manson", "Brandon Montour", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Daniel Sprong", "Andy Welinski"]}
{"game_date": "December 27, 2018, 10:30 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Jake Dotchin", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Mahura", "Josh Manson", "Brandon Montour", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Daniel Sprong"]}
{"game_date": "December 31, 2018, 8:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Mahura", "Josh Manson", "Brandon Montour", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Daniel Sprong", "Andy Welinski"]}
{"game_date": "December 29, 2018, 10:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Ryan Getzlaf", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Mahura", "Josh Manson", "Brandon Montour", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Daniel Sprong", "Ben Street", "Andy Welinski"]}
{"game_date": "December 22, 2018, 7:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Jake Dotchin", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Mahura", "Josh Manson", "Brandon Montour", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Daniel Sprong"]}
{"game_date": "December 18, 2018, 7:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Jake Dotchin", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Mahura", "Josh Manson", "Brandon Montour", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Daniel Sprong"]}
{"game_date": "December 17, 2018, 7:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Jake Dotchin", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Mahura", "Josh Manson", "Brandon Montour", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Daniel Sprong"]}
{"game_date": "December 15, 2018, 7:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Jake Dotchin", "Ryan Getzlaf", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Mahura", "Josh Manson", "Brandon Montour", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Daniel Sprong", "Ben Street"]}
{"game_date": "December 12, 2018, 10:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Jake Dotchin", "Ryan Getzlaf", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Mahura", "Josh Manson", "Brandon Montour", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Daniel Sprong", "Ben Street"]}
{"game_date": "December 9, 2018, 8:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Jake Dotchin", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Mahura", "Josh Manson", "Brandon Montour", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Daniel Sprong"]}
{"game_date": "November 30, 2018, 7:30 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Jake Dotchin", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg"]}
{"game_date": "December 5, 2018, 10:30 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Jake Dotchin", "Ryan Getzlaf", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Mahura", "Josh Manson", "Brandon Montour", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Daniel Sprong"]}
{"game_date": "November 27, 2018, 7:30 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Jake Dotchin", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Andy Welinski"]}
{"game_date": "December 2, 2018, 3:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Jake Dotchin", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg"]}
{"game_date": "November 25, 2018, 8:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Jake Dotchin", "Ryan Getzlaf", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Kalle Kossila", "Jacob Larsson", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Nick Ritchie", "Kiefer Sherwood", "Jakob Silfverberg", "Ben Street", "Andrej Sustr"]}
{"game_date": "December 7, 2018, 10:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Jake Dotchin", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Josh Mahura", "Josh Manson", "Brandon Montour", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Daniel Sprong"]}
{"game_date": "November 23, 2018, 4:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Jake Dotchin", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Kalle Kossila", "Jacob Larsson", "Josh Mahura", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Nick Ritchie", "Kiefer Sherwood", "Jakob Silfverberg"]}
{"game_date": "November 28, 2018, 7:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Jake Dotchin", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Jacob Larsson", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Nick Ritchie", "Carter Rowney", "Kiefer Sherwood", "Jakob Silfverberg", "Andy Welinski"]}
{"game_date": "November 21, 2018, 10:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Kalle Kossila", "Jacob Larsson", "Josh Mahura", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Nick Ritchie", "Kiefer Sherwood", "Jakob Silfverberg", "Andy Welinski"]}
{"game_date": "November 14, 2018, 10:30 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Kalle Kossila", "Jacob Larsson", "Hampus Lindholm", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Nick Ritchie", "Kiefer Sherwood", "Jakob Silfverberg", "Andy Welinski"]}
{"game_date": "November 18, 2018, 8:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Kalle Kossila", "Jacob Larsson", "Josh Mahura", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Nick Ritchie", "Kiefer Sherwood", "Jakob Silfverberg", "Andy Welinski"]}
{"game_date": "November 16, 2018, 10:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Kalle Kossila", "Jacob Larsson", "Hampus Lindholm", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Nick Ritchie", "Kiefer Sherwood", "Jakob Silfverberg", "Andy Welinski"]}
{"game_date": "November 12, 2018, 10:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Cam Fowler", "Ryan Getzlaf", "Brian Gibbons", "Adam Henrique", "Ondrej Kase", "Ryan Kesler", "Kalle Kossila", "Jacob Larsson", "Hampus Lindholm", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Nick Ritchie", "Kiefer Sherwood", "Jakob Silfverberg"]}
{"game_date": "November 7, 2018, 10:30 PM", "skater_list": ["", "Pontus Aberg", "Sam Carrick", "Andrew Cogliano", "Patrick Eaves", "Cam Fowler", "Ryan Getzlaf", "Adam Henrique", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Isac Lundestrom", "Josh Manson", "Brandon Montour", "Marcus Pettersson", "Rickard Rakell", "Kiefer Sherwood", "Jakob Silfverberg", "Ben Street"]}
{"game_date": "November 9, 2018, 10:00 PM", "skater_list": ["", "Pontus Aberg", "Andrew Cogliano", "Patrick Eaves", "Cam Fowler", "Ryan Getzlaf", "Adam Henrique", "Ryan Kesler", "Jacob Larsson", "Hampus Lindholm", "Isac Lundestrom", "Josh Manson", "Brandon Montour", "Rickard Rakell", "Nick Ritchie", "Luke Schenn", "Kiefer Sherwood", "Jakob Silfverberg", "Ben Street"]}
